<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ShopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $shops = [
            [
                'name' => 'Tech Zone Colombo',
                'slug' => 'tech-zone-colombo',
                'description' => 'Latest electronics and gadgets in Colombo',
                'owner_id' => 2,
                'address' => '123 Galle Road, Colombo 03',
                'latitude' => 6.9271,
                'longitude' => 79.8612,
                'phone' => '+94112345678',
                'email' => 'info@techzone.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Fashion Hub Kandy',
                'slug' => 'fashion-hub-kandy',
                'description' => 'Trendy clothing and accessories',
                'owner_id' => 3,
                'address' => '45 Dalada Veediya, Kandy',
                'latitude' => 7.2906,
                'longitude' => 80.6337,
                'phone' => '+94812234567',
                'email' => 'contact@fashionhub.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Spice Garden Restaurant',
                'slug' => 'spice-garden-restaurant',
                'description' => 'Authentic Sri Lankan cuisine',
                'owner_id' => 4,
                'address' => '78 Negombo Road, Colombo 13',
                'latitude' => 6.9897,
                'longitude' => 79.8859,
                'phone' => '+94112987654',
                'email' => 'info@spicegarden.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Book Haven Galle',
                'slug' => 'book-haven-galle',
                'description' => 'Wide selection of books and stationery',
                'owner_id' => 5,
                'address' => '23 Church Street, Galle Fort',
                'latitude' => 6.0267,
                'longitude' => 80.2170,
                'phone' => '+94912234567',
                'email' => 'books@bookhaven.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Fresh Mart Negombo',
                'slug' => 'fresh-mart-negombo',
                'description' => 'Fresh groceries and daily essentials',
                'owner_id' => 6,
                'address' => '156 Main Street, Negombo',
                'latitude' => 7.2097,
                'longitude' => 79.8358,
                'phone' => '+94312234567',
                'email' => 'info@freshmart.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Home Decor Paradise',
                'slug' => 'home-decor-paradise',
                'description' => 'Furniture and home decorations',
                'owner_id' => 7,
                'address' => '89 Baseline Road, Colombo 09',
                'latitude' => 6.8905,
                'longitude' => 79.8573,
                'phone' => '+94112876543',
                'email' => 'info@homedecor.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Gaming World Maharagama',
                'slug' => 'gaming-world-maharagama',
                'description' => 'Gaming consoles, games and accessories',
                'owner_id' => 8,
                'address' => '34 High Level Road, Maharagama',
                'latitude' => 6.8489,
                'longitude' => 79.9267,
                'phone' => '+94112765432',
                'email' => 'info@gamingworld.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Beauty Lounge Nugegoda',
                'slug' => 'beauty-lounge-nugegoda',
                'description' => 'Premium cosmetics and skincare products',
                'owner_id' => 9,
                'address' => '67 Stanley Thilakaratne Mawatha, Nugegoda',
                'latitude' => 6.8649,
                'longitude' => 79.8997,
                'phone' => '+94112654321',
                'email' => 'info@beautylounge.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Mobile Store Matara',
                'slug' => 'mobile-store-matara',
                'description' => 'Latest smartphones and accessories',
                'owner_id' => 10,
                'address' => '12 Anagarika Dharmapala Mawatha, Matara',
                'latitude' => 5.9549,
                'longitude' => 80.5550,
                'phone' => '+94412234567',
                'email' => 'info@mobilestore.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Cafe Aroma Colombo',
                'slug' => 'cafe-aroma-colombo',
                'description' => 'Premium coffee and bakery items',
                'owner_id' => 2,
                'address' => '45 Duplication Road, Colombo 04',
                'latitude' => 6.8942,
                'longitude' => 79.8562,
                'phone' => '+94112543210',
                'email' => 'info@cafearoma.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Sports Zone Kurunegala',
                'slug' => 'sports-zone-kurunegala',
                'description' => 'Sports equipment and athletic wear',
                'owner_id' => 3,
                'address' => '78 Colombo Road, Kurunegala',
                'latitude' => 7.4867,
                'longitude' => 80.3647,
                'phone' => '+94372234567',
                'email' => 'info@sportszone.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Kids Corner Jaffna',
                'slug' => 'kids-corner-jaffna',
                'description' => 'Toys, books and children\'s clothing',
                'owner_id' => 4,
                'address' => '23 Hospital Road, Jaffna',
                'latitude' => 9.6615,
                'longitude' => 80.0255,
                'phone' => '+94212234567',
                'email' => 'info@kidscorner.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Organic Farm Shop',
                'slug' => 'organic-farm-shop',
                'description' => 'Organic vegetables and fruits',
                'owner_id' => 5,
                'address' => '56 Peradeniya Road, Kandy',
                'latitude' => 7.2571,
                'longitude' => 80.5910,
                'phone' => '+94812876543',
                'email' => 'info@organicfarm.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Tech Repairs Colombo',
                'slug' => 'tech-repairs-colombo',
                'description' => 'Electronics repair and services',
                'owner_id' => 6,
                'address' => '90 Union Place, Colombo 02',
                'latitude' => 6.9147,
                'longitude' => 79.8501,
                'phone' => '+94112765432',
                'email' => 'info@techrepairs.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Pet Paradise Moratuwa',
                'slug' => 'pet-paradise-moratuwa',
                'description' => 'Pet supplies and accessories',
                'owner_id' => 7,
                'address' => '34 Galle Road, Moratuwa',
                'latitude' => 6.7733,
                'longitude' => 79.8816,
                'phone' => '+94112654321',
                'email' => 'info@petparadise.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Jewelry Palace Colombo',
                'slug' => 'jewelry-palace-colombo',
                'description' => 'Gold, silver and precious stones',
                'owner_id' => 8,
                'address' => '12 Sea Street, Colombo 11',
                'latitude' => 6.9497,
                'longitude' => 79.8536,
                'phone' => '+94112543210',
                'email' => 'info@jewelrypalace.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Fitness First Battaramulla',
                'slug' => 'fitness-first-battaramulla',
                'description' => 'Gym equipment and supplements',
                'owner_id' => 9,
                'address' => '45 Pannipitiya Road, Battaramulla',
                'latitude' => 6.8986,
                'longitude' => 79.9181,
                'phone' => '+94112432109',
                'email' => 'info@fitnessfirst.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Art Supplies Hub',
                'slug' => 'art-supplies-hub',
                'description' => 'Professional art materials and craft supplies',
                'owner_id' => 10,
                'address' => '67 Ananda Coomaraswamy Mawatha, Colombo 07',
                'latitude' => 6.9132,
                'longitude' => 79.8610,
                'phone' => '+94112321098',
                'email' => 'info@artsupplies.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Music Store Colombo',
                'slug' => 'music-store-colombo',
                'description' => 'Musical instruments and accessories',
                'owner_id' => 2,
                'address' => '89 Thimbirigasyaya Road, Colombo 05',
                'latitude' => 6.8874,
                'longitude' => 79.8654,
                'phone' => '+94112210987',
                'email' => 'info@musicstore.lk',
                'status' => 'active',
            ],
            [
                'name' => 'Ayurveda Center Gampaha',
                'slug' => 'ayurveda-center-gampaha',
                'description' => 'Traditional ayurvedic products and treatments',
                'owner_id' => 3,
                'address' => '23 Main Street, Gampaha',
                'latitude' => 7.0908,
                'longitude' => 79.9999,
                'phone' => '+94332234567',
                'email' => 'info@ayurvedacenter.lk',
                'status' => 'active',
            ],
        ];

        foreach ($shops as $shopData) {
            \App\Models\Shop::create($shopData);
        }

        $this->command->info('Shops seeded successfully!');
    }
}
